import Head from "next/head";
import { Inter } from "@next/font/google";
import Navbar from "@/components/navbar/Navbar";
import Hero from "@/components/hero/Hero";
import Services from "@/components/services/Services";
import OurRoom from "@/components/ourRoom/OurRoom";
import AboutUs from "@/components/AboutUs";
import Interior from "@/components/interior/Interior";
import Footer from "@/components/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="max-w-screen-2xl m-auto">
        <Navbar />
        <Hero />
        <Services />
        <OurRoom />
        <AboutUs />
        <Interior />
        <Footer />
      </div>
    </>
  );
}
